[package]
name = "animatix"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
chrono = "0.4.44"
chumsky = "0.12.0"
clap = { version = "4.5.0", features = ["derive"] }
fontdue = "0.9.3"
image = "0.25.10"
kurbo = "0.13.0"
mitex = "0.2.4"
pollster = "0.4.0"
rand = "0.10.0"
rsmpeg = { version = "0.18.0", default-features = false, features = ["ffmpeg7_1", "link_system_ffmpeg"] }
ttf-parser = "0.25.1"
typst = "0.14.2"
typst-layout = "0.14.2"
typst-syntax = "0.14.2"
usvg = "0.47.0"
vello = "0.8.0"
wgpu = "28.0.0"
winit = "0.30.13"
