[package]
name = "animatix-gui"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
default-run = "animatix-gui"

[features]
default = []
video = ["animatix/video"]

[dependencies]
animatix = { path = "../animatix" }
animatix-analyzer = { path = "../animatix-analyzer" }
animatix-syntax = { path = "../animatix-syntax" }
crossbeam-channel = "0.5"
directories = "6.0.0"
eframe = { version = "0.34", default-features = false, features = ["default_fonts", "wgpu", "x11", "wayland"] }
egui = { version = "0.34", features = ["serde"] }
egui_code_editor = { version = "0.2", features = ["editor", "egui"] }
egui_extras = { version = "0.34", features = ["syntect"] }
egui_tiles = { version = "0.15", features = ["serde"] }
egui-phosphor = { version = "0.12", default-features = false, features = ["regular"] }
kurbo = "0.13.0"
pollster = "0.4.0"
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
syntect = { version = "5.3.0", features = ["default-fancy", "yaml-load"] }
thiserror = "2.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
notify = { version = "7.0.0", default-features = false, features = ["macos_fsevent"] }
rfd = "0.15"
rodio = "0.20"
tree-sitter = "0.26"
tree-sitter-animatix = { path = "../tree-sitter-animatix" }
tree-sitter-highlight = "0.26"
wgpu = "29.0.0"

[dev-dependencies]
chumsky = "0.12"
