//! JSON theme loading and schema support (`theme-json` feature).
//!
//! The serialized format keeps the runtime [`Theme`] representation as a DTO:
//! colors are hex strings (`#rrggbb` or `#rrggbbaa`) and shadows are small
//! objects (`{ "offset": [x, y], "blur": n, "spread": n, "color": "#..." }`).
//!
//! A theme file can carry both modes:
//! ```json
//! {
//!   "name": "My Theme",
//!   "dark": { "surface": { "base": "#202124" }, ... },
//!   "light": { "surface": { "base": "#f8f9fa" }, ... }
//! }
//! ```

use std::path::Path;

use egui::{Color32, Shadow};
use serde::{Deserialize, Serialize};

use super::theme::{
    Accent, AlertLevelSlots, AlertSlots, Border, ButtonSlots, ButtonStateSlots, ColorPickerSlots,
    EasingCurveSlots, Elevation, Fill, InputSlots, Lines, ListSlots, MenuItemSlots, Overlay,
    ProgressSlots, ScrollbarSlots, SkeletonSlots, Slot, Status, Surface, TabSlot, TabSlots,
    TagSlots, Text, Theme, ToastLevelSlots, ToastSlots, ToggleSlots, serde_color32, serde_shadow,
};

/// A single dark/light theme file.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ThemeFile {
    /// Optional display name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Optional name of another theme in the same registry that this theme
    /// extends. Missing fields inherit from the resolved base theme.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extends: Option<String>,
    /// Dark-mode theme. Omitted fields fall back to the resolved base.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dark: Option<PartialTheme>,
    /// Light-mode theme. Omitted fields fall back to the resolved base.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub light: Option<PartialTheme>,
}

// `PartialTheme` and every nested `Partial*` type are generated by the
// `partial_group!` invocations below (see "Partial-field bridging"). The
// generated `PartialTheme` keeps the same field names, `deny_unknown_fields`,
// and omit-when-`None` representation as the previous hand-written struct.

// ── Partial-field bridging ────────────────────────────────────────────
//
// Every full token type implements `PartialField`, mapping itself to the
// wire representation used by its `Partial*` counterpart. The `partial_group!`
// macro below then derives each `Partial*` struct, its `apply_to`/`from_full`
// glue, and the `PartialField` impl from a single field list, so adding a token
// is a one-line edit instead of edits in 4+ places.

/// A full token type that has a `Partial*` wire counterpart.
///
/// `Partial` is the type stored inside the `Option<..>` fields of the
/// corresponding `Partial*` struct (`Color32Field` for `Color32`,
/// `PartialSlot` for `Slot`, …). The methods are the only place a full token
/// reads from / writes to its partial form, which keeps `apply_to` and
/// `from_full` behaviourally identical across every group.
pub trait PartialField: Sized {
    /// The partial (all-optional) representation of this type.
    type Partial;

    /// Apply a present partial value onto the full value.
    fn apply_field(partial: Self::Partial, target: &mut Self);

    /// Capture the full value as its partial representation.
    fn to_partial(&self) -> Self::Partial;
}

// The `Color32Field` one-field wrapper keeps `serde_color32` compatible with
// optional fields while the helper remains available for non-optional colors.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Color32Field(pub egui::Color32);

impl Serialize for Color32Field {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde_color32::serialize(&self.0, serializer)
    }
}

impl<'de> Deserialize<'de> for Color32Field {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(Self(serde_color32::deserialize(deserializer)?))
    }
}

impl From<egui::Color32> for Color32Field {
    fn from(value: egui::Color32) -> Self {
        Self(value)
    }
}

impl PartialField for egui::Color32 {
    type Partial = Color32Field;

    fn apply_field(partial: Self::Partial, target: &mut Self) {
        *target = partial.0;
    }

    fn to_partial(&self) -> Self::Partial {
        Color32Field(*self)
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct ShadowField(pub Shadow);

impl Serialize for ShadowField {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde_shadow::serialize(&self.0, serializer)
    }
}

impl<'de> Deserialize<'de> for ShadowField {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(Self(serde_shadow::deserialize(deserializer)?))
    }
}

impl From<Shadow> for ShadowField {
    fn from(value: Shadow) -> Self {
        Self(value)
    }
}

impl PartialField for Shadow {
    type Partial = ShadowField;

    fn apply_field(partial: Self::Partial, target: &mut Self) {
        *target = partial.0;
    }

    fn to_partial(&self) -> Self::Partial {
        ShadowField(*self)
    }
}

/// Generate a `Partial*` mirror of a token struct plus its merge/extract glue.
///
/// Given a full type and a field list, this emits:
/// - `Partial<Full>` with an `Option<<FieldTy as PartialField>::Partial>` per field,
///   `#[serde(default, skip_serializing_if = "Option::is_none")]`, and
///   `#[serde(deny_unknown_fields)]` (matching the hand-written structs it replaces);
/// - a private `apply_fields(self, &mut Full)` that merges only the fields present in the partial
///   (the merge primitive every other method delegates to);
/// - a public `apply_to` whose signature depends on the arm: `&mut Full` for nested groups, `Full
///   -> Full` for the `@root` arm so `PartialTheme` keeps its historical by-value `apply_to(base)
///   -> Theme`;
/// - `from_full(&Full) -> Self`;
/// - `impl PartialField for Full`.
///
/// Field types are the *full* types; their partial counterparts are resolved
/// through `PartialField::Partial`, so one invocation covers groups of colors,
/// nested slots, and shadows alike.
macro_rules! partial_group {
    // Root arm: the top-level `Theme` → `PartialTheme`. The wire shape stays
    // flat (one struct field per top-level group) while each group routes into
    // its nested home inside `Theme` (`palette.*` / `components.*`). Fields are
    // written `name => path.to.field : Type`, so the partial's key (and thus the
    // JSON key) is `name` but reads/writes go through the dotted path.
    (
        @root
        $(#[$meta:meta])*
        $full:ident => $partial:ident
        { $( $field:ident => $($path:ident).+ : $ty:ty ),* $(,)? }
    ) => {
        partial_group!(@fields
            $(#[$meta])*
            $full => $partial
            { $( $field => $($path).+ : $ty ),* }
        );

        impl $partial {
            /// Apply this partial theme over `base`, returning the merged theme.
            pub fn apply_to(self, mut base: $full) -> $full {
                self.apply_fields(&mut base);
                base
            }

            /// Convert a full theme into a partial override with every field
            /// populated. This is useful for canonical export files.
            pub fn full_from(theme: $full) -> Self {
                Self::from_full(&theme)
            }
        }
    };

    (
        $(#[$meta:meta])*
        $full:ident => $partial:ident
        { $( $field:ident : $ty:ty ),* $(,)? }
    ) => {
        partial_group!(@fields
            $(#[$meta])*
            $full => $partial
            { $( $field : $ty ),* }
        );

        impl $partial {
            /// Apply every field present in this partial onto `target`,
            /// leaving absent fields untouched.
            pub fn apply_to(self, target: &mut $full) {
                self.apply_fields(target);
            }
        }
    };

    (
        @fields
        $(#[$meta:meta])*
        $full:ident => $partial:ident
        { $( $field:ident => $($path:ident).+ : $ty:ty ),* $(,)? }
    ) => {
        $(#[$meta])*
        #[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
        #[serde(deny_unknown_fields)]
        pub struct $partial {
            $(
                #[serde(default, skip_serializing_if = "Option::is_none")]
                pub $field: Option<<$ty as PartialField>::Partial>,
            )*
        }

        impl $partial {
            /// Apply each present field onto `target`; absent fields are left as-is.
            fn apply_fields(self, target: &mut $full) {
                $(
                    if let Some(value) = self.$field {
                        <$ty as PartialField>::apply_field(value, &mut target.$($path).+);
                    }
                )*
            }

            /// Capture every field of `full` into this partial.
            pub fn from_full(full: &$full) -> Self {
                Self {
                    $( $field: Some(<$ty as PartialField>::to_partial(&full.$($path).+)), )*
                }
            }
        }

        impl PartialField for $full {
            type Partial = $partial;

            fn apply_field(partial: Self::Partial, target: &mut Self) {
                partial.apply_fields(target);
            }

            fn to_partial(&self) -> Self::Partial {
                $partial::from_full(self)
            }
        }
    };

    (
        @fields
        $(#[$meta:meta])*
        $full:ident => $partial:ident
        { $( $field:ident : $ty:ty ),* $(,)? }
    ) => {
        $(#[$meta])*
        #[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
        #[serde(deny_unknown_fields)]
        pub struct $partial {
            $(
                #[serde(default, skip_serializing_if = "Option::is_none")]
                pub $field: Option<<$ty as PartialField>::Partial>,
            )*
        }

        impl $partial {
            /// Apply each present field onto `target`; absent fields are left as-is.
            fn apply_fields(self, target: &mut $full) {
                $(
                    if let Some(value) = self.$field {
                        <$ty as PartialField>::apply_field(value, &mut target.$field);
                    }
                )*
            }

            /// Capture every field of `full` into this partial.
            pub fn from_full(full: &$full) -> Self {
                Self {
                    $( $field: Some(<$ty as PartialField>::to_partial(&full.$field)), )*
                }
            }
        }

        impl PartialField for $full {
            type Partial = $partial;

            fn apply_field(partial: Self::Partial, target: &mut Self) {
                partial.apply_fields(target);
            }

            fn to_partial(&self) -> Self::Partial {
                $partial::from_full(self)
            }
        }
    };
}

// ── Leaf / component-slot groups ──────────────────────────────────────

partial_group! {
    Slot => PartialSlot
    { bg: egui::Color32, fg: egui::Color32, border: egui::Color32 }
}

partial_group! {
    Fill => PartialFill
    { bg: egui::Color32, fg: egui::Color32 }
}

partial_group! {
    TabSlot => PartialTabSlot
    { bg: egui::Color32, fg: egui::Color32, indicator: egui::Color32 }
}

partial_group! {
    ScrollbarSlots => PartialScrollbarSlots
    { thumb: egui::Color32, thumb_hover: egui::Color32 }
}

partial_group! {
    Elevation => PartialElevation
    { raised: Shadow, overlay: Shadow }
}

// ── Group partials + root `PartialTheme` (generated) ──────────────────
//
// Each invocation below replaces a hand-written `Partial*` struct + `apply_to`
// + `from_full`. Adding a token to a group is now a single field-list edit, and
// the nested types bridge through their own `PartialField` impls.

partial_group! {
    Surface => PartialSurface
    {
        base: Color32,
        panel: Color32,
        surface: Color32,
        widget: Color32,
        hover: Color32,
        active: Color32,
        floating_card_bg: Color32,
    }
}

partial_group! {
    Text => PartialText
    {
        primary: Color32,
        secondary: Color32,
        muted: Color32,
        disabled: Color32,
        on_accent: Color32,
        faint: Color32,
        subtle: Color32,
        hover: Color32,
        dim: Color32,
    }
}

partial_group! {
    Accent => PartialAccent
    {
        primary: Color32,
        cyan: Color32,
        primary_hover: Color32,
        primary_active: Color32,
        faint: Color32,
        ghost: Color32,
        subtle: Color32,
        hover: Color32,
        strong: Color32,
        selection: Color32,
    }
}

partial_group! {
    Status => PartialStatus
    {
        success: Color32,
        warning: Color32,
        error: Color32,
        info: Color32,
        playing_text: Color32,
        diagnostic_error: Color32,
        diagnostic_warning: Color32,
        success_faint: Color32,
        success_ultra_faint: Color32,
        warning_subtle: Color32,
        error_faint: Color32,
        error_ultra_faint: Color32,
    }
}

partial_group! {
    Border => PartialBorder
    { default: Color32, strong: Color32, focus: Color32 }
}

partial_group! {
    Overlay => PartialOverlay
    {
        backdrop: Color32,
        badge_bg: Color32,
        tooltip_bg: Color32,
        shadow_ambient: Color32,
        shadow_direct: Color32,
    }
}

partial_group! {
    Lines => PartialLines
    { grid: Color32, guide: Color32 }
}

partial_group! {
    ButtonStateSlots => PartialButtonStateSlots
    {
        normal: Slot,
        hover: Slot,
        active: Slot,
        selected: Slot,
        disabled: Slot,
        focus: Slot,
    }
}

partial_group! {
    ButtonSlots => PartialButtonSlots
    {
        primary: ButtonStateSlots,
        secondary: ButtonStateSlots,
        ghost: ButtonStateSlots,
        icon: ButtonStateSlots,
        danger: ButtonStateSlots,
    }
}

partial_group! {
    ListSlots => PartialListSlots
    { even: Fill, odd: Fill, selected: Fill, hover: Fill }
}

partial_group! {
    TabSlots => PartialTabSlots
    { active: TabSlot, inactive: TabSlot, hover: TabSlot }
}

partial_group! {
    MenuItemSlots => PartialMenuItemSlots
    { normal: Slot, hover: Slot, active: Slot, disabled: Slot }
}

partial_group! {
    InputSlots => PartialInputSlots
    { normal: Slot, hover: Slot, focus: Slot, invalid: Slot, disabled: Slot }
}

// Per-component groups for widgets that previously picked colours directly.
partial_group! {
    ToggleSlots => PartialToggleSlots
    {
        checked: Slot,
        unchecked: Slot,
        hover: Slot,
        disabled: Slot,
        thumb: Color32,
        mark: Color32,
    }
}

partial_group! {
    ProgressSlots => PartialProgressSlots
    { track: Color32, fill: Color32, label: Color32, label_on_fill: Color32 }
}

partial_group! {
    TagSlots => PartialTagSlots
    { normal: Slot, hover: Slot }
}

partial_group! {
    AlertLevelSlots => PartialAlertLevelSlots
    { bg: Color32, fg: Color32, accent: Color32, icon: Color32 }
}

partial_group! {
    AlertSlots => PartialAlertSlots
    { info: AlertLevelSlots, success: AlertLevelSlots, warning: AlertLevelSlots, error: AlertLevelSlots }
}

partial_group! {
    ToastLevelSlots => PartialToastLevelSlots
    { bg: Color32, fg: Color32, border: Color32, accent: Color32 }
}

partial_group! {
    ToastSlots => PartialToastSlots
    { info: ToastLevelSlots, success: ToastLevelSlots, warning: ToastLevelSlots, error: ToastLevelSlots }
}

partial_group! {
    SkeletonSlots => PartialSkeletonSlots
    { base: Color32, shimmer: Color32 }
}

partial_group! {
    ColorPickerSlots => PartialColorPickerSlots
    {
        swatch_border: Color32,
        swatch_hover: Color32,
        checker_light: Color32,
        checker_dark: Color32,
    }
}

partial_group! {
    EasingCurveSlots => PartialEasingCurveSlots
    { bg: Color32, grid: Color32, curve: Color32, handle: Color32, handle_active: Color32 }
}

partial_group!(@root
    Theme => PartialTheme
    {
        surface => palette.surface: Surface,
        text => palette.text: Text,
        accent => palette.accent: Accent,
        status => palette.status: Status,
        border => palette.border: Border,
        overlay => palette.overlay: Overlay,
        lines => palette.lines: Lines,
        button => components.button: ButtonSlots,
        list => components.list: ListSlots,
        tab => components.tab: TabSlots,
        menu_item => components.menu_item: MenuItemSlots,
        input => components.input: InputSlots,
        scrollbar => components.scrollbar: ScrollbarSlots,
        toggle => components.toggle: ToggleSlots,
        progress => components.progress: ProgressSlots,
        badge => components.badge: Slot,
        tag => components.tag: TagSlots,
        kbd => components.kbd: Slot,
        tooltip => components.tooltip: Slot,
        alert => components.alert: AlertSlots,
        toast => components.toast: ToastSlots,
        skeleton => components.skeleton: SkeletonSlots,
        color_picker => components.color_picker: ColorPickerSlots,
        easing_curve => components.easing_curve: EasingCurveSlots,
        elevation => elevation: Elevation,
    }
);

impl ThemeFile {
    /// Build a `ThemeFile` from the built-in dark and light themes.
    pub fn builtin() -> Self {
        Self {
            name: Some("Animatix".to_string()),
            extends: None,
            dark: Some(PartialTheme::full_from(Theme::dark())),
            light: Some(PartialTheme::full_from(Theme::light())),
        }
    }

    /// Resolve the dark theme, falling back to built-in dark.
    pub fn dark_theme(&self) -> Theme {
        self.dark.clone().unwrap_or_default().apply_to(Theme::dark())
    }

    /// Resolve the light theme, falling back to built-in light.
    pub fn light_theme(&self) -> Theme {
        self.light.clone().unwrap_or_default().apply_to(Theme::light())
    }

    /// Parse a theme file from JSON.
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    /// Serialize this theme file as pretty JSON.
    pub fn to_json_pretty(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Load a theme file from disk.
    pub fn load(path: &Path) -> Result<Self, ThemeJsonError> {
        let source = std::fs::read_to_string(path).map_err(ThemeJsonError::Io)?;
        Self::from_json(&source).map_err(ThemeJsonError::Json)
    }

    /// Save this theme file to disk.
    pub fn save(&self, path: &Path) -> Result<(), ThemeJsonError> {
        let source = self.to_json_pretty().map_err(ThemeJsonError::Json)?;
        std::fs::write(path, source).map_err(ThemeJsonError::Io)
    }
}

/// A small error type for theme file I/O and JSON parsing.
#[derive(Debug, thiserror::Error)]
pub enum ThemeJsonError {
    #[error("failed to read theme file: {0}")]
    Io(#[from] std::io::Error),
    #[error("invalid theme JSON: {0}")]
    Json(#[from] serde_json::Error),
}

/// JSON Schema for the theme file format.
///
/// The schema is intentionally permissive at the root (string values for every
/// color field) and does not enumerate every nested token individually; editors
/// can use it for basic validation and auto-completion while the Rust DTO
/// remains the authoritative parser.
///
/// **Keep in sync with the `partial_group!` invocations.** This schema is
/// hand-written (not generated from the macro groups); when a group's field
/// list or a `PartialTheme` field name changes, update the matching
/// `$defs`/property entry below. The nested `colorGroup`/`slotSlots`
/// `patternProperties` cover additive color/slot fields automatically, but a
/// *new group name* or a renamed field must be added here by hand.
pub fn theme_schema_json() -> String {
    let schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Animatix Theme",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "name": { "type": "string" },
            "extends": { "type": "string" },
            "dark": { "$ref": "#/$defs/theme" },
            "light": { "$ref": "#/$defs/theme" }
        },
        "$defs": {
            "theme": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "surface": { "$ref": "#/$defs/colorGroup" },
                    "text": { "$ref": "#/$defs/colorGroup" },
                    "accent": { "$ref": "#/$defs/colorGroup" },
                    "status": { "$ref": "#/$defs/colorGroup" },
                    "border": { "$ref": "#/$defs/colorGroup" },
                    "overlay": { "$ref": "#/$defs/colorGroup" },
                    "lines": { "$ref": "#/$defs/colorGroup" },
                    "button": { "$ref": "#/$defs/buttonSlots" },
                    "list": { "$ref": "#/$defs/fillSlots" },
                    "tab": { "$ref": "#/$defs/tabSlots" },
                    "menu_item": { "$ref": "#/$defs/slotSlots" },
                    "input": { "$ref": "#/$defs/slotSlots" },
                    "scrollbar": { "$ref": "#/$defs/scrollbar" },
                    "toggle": { "$ref": "#/$defs/toggleSlots" },
                    "progress": { "$ref": "#/$defs/colorGroup" },
                    "badge": { "$ref": "#/$defs/slot" },
                    "tag": { "$ref": "#/$defs/tagSlots" },
                    "kbd": { "$ref": "#/$defs/slot" },
                    "tooltip": { "$ref": "#/$defs/slot" },
                    "alert": { "$ref": "#/$defs/alertSlots" },
                    "toast": { "$ref": "#/$defs/toastSlots" },
                    "skeleton": { "$ref": "#/$defs/colorGroup" },
                    "color_picker": { "$ref": "#/$defs/colorGroup" },
                    "easing_curve": { "$ref": "#/$defs/colorGroup" },
                    "elevation": { "$ref": "#/$defs/elevation" }
                }
            },
            "colorGroup": {
                "type": "object",
                "additionalProperties": false,
                "patternProperties": {
                    "^[a-z_]+$": { "type": "string" }
                }
            },
            "toggleSlots": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "checked": { "$ref": "#/$defs/slot" },
                    "unchecked": { "$ref": "#/$defs/slot" },
                    "hover": { "$ref": "#/$defs/slot" },
                    "disabled": { "$ref": "#/$defs/slot" },
                    "thumb": { "type": "string" },
                    "mark": { "type": "string" }
                }
            },
            "tagSlots": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "normal": { "$ref": "#/$defs/slot" },
                    "hover": { "$ref": "#/$defs/slot" }
                }
            },
            "alertLevel": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "bg": { "type": "string" },
                    "fg": { "type": "string" },
                    "accent": { "type": "string" },
                    "icon": { "type": "string" }
                }
            },
            "alertSlots": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "info": { "$ref": "#/$defs/alertLevel" },
                    "success": { "$ref": "#/$defs/alertLevel" },
                    "warning": { "$ref": "#/$defs/alertLevel" },
                    "error": { "$ref": "#/$defs/alertLevel" }
                }
            },
            "toastLevel": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "bg": { "type": "string" },
                    "fg": { "type": "string" },
                    "border": { "type": "string" },
                    "accent": { "type": "string" }
                }
            },
            "toastSlots": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "info": { "$ref": "#/$defs/toastLevel" },
                    "success": { "$ref": "#/$defs/toastLevel" },
                    "warning": { "$ref": "#/$defs/toastLevel" },
                    "error": { "$ref": "#/$defs/toastLevel" }
                }
            },
            "slot": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "bg": { "type": "string" },
                    "fg": { "type": "string" },
                    "border": { "type": "string" }
                }
            },
            "fill": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "bg": { "type": "string" },
                    "fg": { "type": "string" }
                }
            },
            "tab": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "bg": { "type": "string" },
                    "fg": { "type": "string" },
                    "indicator": { "type": "string" }
                }
            },
            "buttonState": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "normal": { "$ref": "#/$defs/slot" },
                    "hover": { "$ref": "#/$defs/slot" },
                    "active": { "$ref": "#/$defs/slot" },
                    "selected": { "$ref": "#/$defs/slot" },
                    "disabled": { "$ref": "#/$defs/slot" },
                    "focus": { "$ref": "#/$defs/slot" }
                }
            },
            "buttonSlots": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "primary": { "$ref": "#/$defs/buttonState" },
                    "secondary": { "$ref": "#/$defs/buttonState" },
                    "ghost": { "$ref": "#/$defs/buttonState" },
                    "icon": { "$ref": "#/$defs/buttonState" },
                    "danger": { "$ref": "#/$defs/buttonState" }
                }
            },
            "fillSlots": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "even": { "$ref": "#/$defs/fill" },
                    "odd": { "$ref": "#/$defs/fill" },
                    "selected": { "$ref": "#/$defs/fill" },
                    "hover": { "$ref": "#/$defs/fill" }
                }
            },
            "tabSlots": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "active": { "$ref": "#/$defs/tab" },
                    "inactive": { "$ref": "#/$defs/tab" },
                    "hover": { "$ref": "#/$defs/tab" }
                }
            },
            "slotSlots": {
                "type": "object",
                "additionalProperties": false,
                "patternProperties": {
                    "^[a-z_]+$": { "$ref": "#/$defs/slot" }
                }
            },
            "scrollbar": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "thumb": { "type": "string" },
                    "thumb_hover": { "type": "string" }
                }
            },
            "elevation": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "raised": { "$ref": "#/$defs/shadow" },
                    "overlay": { "$ref": "#/$defs/shadow" }
                }
            },
            "shadow": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "offset": {
                        "type": "array",
                        "items": { "type": "integer" },
                        "minItems": 2,
                        "maxItems": 2
                    },
                    "blur": { "type": "integer" },
                    "spread": { "type": "integer" },
                    "color": { "type": "string" }
                }
            }
        }
    });
    serde_json::to_string_pretty(&schema).expect("theme schema is valid JSON")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The macro guard: `full_from` must populate every field, and applying the
    /// result back over a *default* theme must reproduce the original exactly.
    /// If `partial_group!` ever drops a field (or forgets to bridge a leaf type),
    /// the defaulted base shows through and this fails.
    fn assert_full_round_trip(original: Theme) {
        let partial = PartialTheme::full_from(original);
        // Every field is present (not the all-empty `PartialTheme::default()`).
        assert_ne!(partial, PartialTheme::default(), "full_from produced no fields");
        let restored = partial.apply_to(Theme::default());
        assert_eq!(restored, original, "full_from -> apply_to(default) changed the theme");
    }

    #[test]
    fn full_from_round_trips_dark_theme() {
        assert_full_round_trip(Theme::dark());
    }

    #[test]
    fn full_from_round_trips_light_theme() {
        assert_full_round_trip(Theme::light());
    }

    /// `apply_to` with an empty partial must be an identity merge over any base.
    #[test]
    fn empty_partial_is_identity() {
        assert_eq!(PartialTheme::default().apply_to(Theme::dark()), Theme::dark());
        assert_eq!(PartialTheme::default().apply_to(Theme::light()), Theme::light());
    }

    #[test]
    fn builtin_theme_file_roundtrips_both_modes() {
        let file = ThemeFile::builtin();
        let json = file.to_json_pretty().expect("serialize");
        let parsed = ThemeFile::from_json(&json).expect("parse");
        assert_eq!(parsed.dark_theme(), Theme::dark());
        assert_eq!(parsed.light_theme(), Theme::light());
        assert_eq!(parsed.name.as_deref(), Some("Animatix"));
    }

    #[test]
    fn partial_override_keeps_unset_dark_tokens() {
        let json = r##"{
            "name": "Custom",
            "dark": { "surface": { "base": "#112233" } }
        }"##;
        let file = ThemeFile::from_json(json).expect("parse");
        let theme = file.dark_theme();
        assert_eq!(theme.palette.surface.base, egui::Color32::from_rgb(0x11, 0x22, 0x33));
        assert_eq!(theme.palette.surface.panel, Theme::dark().palette.surface.panel);
        assert_eq!(theme.palette.text.primary, Theme::dark().palette.text.primary);
        assert_eq!(
            theme.components.button.primary.normal.bg,
            Theme::dark().components.button.primary.normal.bg
        );
        assert_eq!(theme.elevation.raised, Theme::dark().elevation.raised);
    }

    #[test]
    fn nested_slots_and_shadows_roundtrip() {
        let json = r##"{
            "dark": {
                "button": { "primary": { "hover": { "bg": "#ff0000" } } },
                "elevation": { "raised": { "offset": [0, 4], "blur": 8, "spread": 1, "color": "#000000aa" } }
            }
        }"##;
        let file = ThemeFile::from_json(json).expect("parse");
        let theme = file.dark_theme();
        assert_eq!(theme.components.button.primary.hover.bg, egui::Color32::from_rgb(0xff, 0, 0));
        assert_eq!(theme.elevation.raised.offset, [0, 4]);
        assert_eq!(theme.elevation.raised.blur, 8);
        assert_eq!(theme.elevation.raised.spread, 1);
        assert_eq!(
            theme.elevation.raised.color,
            egui::Color32::from_rgba_unmultiplied(0, 0, 0, 0xaa)
        );
    }

    #[test]
    fn unknown_fields_are_rejected() {
        let json = r##"{ "dark": { "unknown_token": "#ff0000" } }"##;
        assert!(ThemeFile::from_json(json).is_err());
    }

    /// The macro must preserve the hand-written wire representation exactly:
    /// absent fields are omitted (not emitted as `null`), present nested groups
    /// use the same key names, and colors serialize as hex strings.
    #[test]
    fn partial_serde_representation_matches_hand_written_shape() {
        // An all-`None` partial serializes to an empty object (omit-when-None).
        assert_eq!(serde_json::to_string(&PartialTheme::default()).unwrap(), "{}");
        assert_eq!(serde_json::to_string(&PartialSlot::default()).unwrap(), "{}");

        // A populated partial emits the original key names and hex colors.
        let partial = PartialTheme::full_from(Theme::dark());
        let value: serde_json::Value = serde_json::to_value(&partial).unwrap();
        let obj = value.as_object().expect("theme object");
        for key in [
            "surface",
            "text",
            "accent",
            "status",
            "border",
            "overlay",
            "lines",
            "button",
            "list",
            "tab",
            "menu_item",
            "input",
            "scrollbar",
            "toggle",
            "progress",
            "badge",
            "tag",
            "kbd",
            "tooltip",
            "alert",
            "toast",
            "skeleton",
            "color_picker",
            "easing_curve",
            "elevation",
        ] {
            assert!(obj.contains_key(key), "missing group {key:?}");
        }
        assert_eq!(value["surface"]["base"], Theme::dark().palette.surface.base.to_hex());
        // A nested slot keeps `bg`/`fg`/`border`, and a nested shadow keeps its
        // object shape (`offset`/`blur`/`spread`/`color`).
        assert!(value["button"]["primary"]["normal"]["bg"].is_string());
        assert!(value["elevation"]["raised"]["offset"].is_array());
    }

    #[test]
    fn invalid_color_is_rejected() {
        let json = r##"{ "dark": { "surface": { "base": "not-a-color" } } }"##;
        assert!(ThemeFile::from_json(json).is_err());
    }

    #[test]
    fn save_and_load_roundtrip() {
        let dir = std::env::temp_dir().join(format!("eparts-theme-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        let path = dir.join("theme.json");
        let file = ThemeFile::builtin();
        file.save(&path).expect("save");
        let loaded = ThemeFile::load(&path).expect("load");
        assert_eq!(loaded.dark_theme(), file.dark_theme());
        assert_eq!(loaded.light_theme(), file.light_theme());
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Serde-compat guard: the checked-in example theme file (which predates the
    /// macro refactor and the new component groups) must keep loading and
    /// merging over the built-in bases.
    #[test]
    fn existing_example_theme_file_still_loads() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/examples/gallery.theme.json");
        let file = ThemeFile::load(Path::new(path)).expect("load gallery.theme.json");
        assert_eq!(file.name.as_deref(), Some("Gallery JSON Theme"));
        let theme = file.dark_theme();
        // The override applies and missing groups inherit the built-in dark base.
        assert_eq!(theme.palette.surface.base, egui::Color32::from_rgb(0x19, 0x1a, 0x1e));
        assert_eq!(
            theme.components.button.primary.normal.bg,
            Theme::dark().components.button.primary.normal.bg
        );
        assert_eq!(theme.components.toggle.checked.bg, Theme::dark().components.toggle.checked.bg);
        assert_eq!(
            theme.components.toast.error.accent,
            Theme::dark().components.toast.error.accent
        );
    }

    #[test]
    fn serialized_theme_json_stays_flat_after_grouping() {
        // The runtime `Theme` gained `palette`/`components` groups, but the
        // on-disk DTO must keep the historical flat shape so existing
        // `theme.json` files (and the schema) stay valid.
        let file = ThemeFile::builtin();
        let json = file.to_json_pretty().expect("serialize");
        let value: serde_json::Value = serde_json::from_str(&json).expect("parse");
        let dark = value["dark"].as_object().expect("dark object");
        for key in [
            "surface", "text", "accent", "status", "border", "overlay", "lines", "button",
        ] {
            assert!(dark.contains_key(key), "missing flat top-level key {key:?}");
        }
        assert!(!dark.contains_key("palette"), "JSON must not nest under `palette`");
        assert!(!dark.contains_key("components"), "JSON must not nest under `components`");
        assert!(dark["surface"]["base"].is_string());
    }

    #[test]
    fn schema_is_valid_json_and_describes_theme_file() {
        let schema = theme_schema_json();
        let value: serde_json::Value = serde_json::from_str(&schema).expect("valid JSON");
        assert_eq!(value["$schema"], "https://json-schema.org/draft/2020-12/schema");
        assert!(value["$defs"]["theme"].is_object());
        assert!(value["$defs"]["elevation"].is_object());
    }
}
