#!/usr/bin/env bash
# Inventory enum/string match sites relevant to the extension abstraction plan.
#
# Usage:
#   scripts/extension-match-inventory.sh
#   scripts/extension-match-inventory.sh --write
#
# --write emits the report to docs/extension_abstraction_inventory.md.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/docs/extension_abstraction_inventory.md"

if [[ "${1:-}" == "--write" ]]; then
    exec > "$OUT"
fi

SEARCH_DIRS=(
    "$ROOT/crates/animatix/src"
    "$ROOT/crates/animatix-gui/src"
    "$ROOT/crates/animatix-syntax/src"
)

count_pattern() {
    local label="$1"
    local pattern="$2"
    shift 2
    local files=("$@")
    local total
    total="$(rg -o --no-filename "$pattern" "${files[@]}" 2>/dev/null | wc -l | tr -d ' ')"
    printf '| %s | %s |\n' "$label" "$total"
}

echo "# Extension Abstraction Match Inventory"
echo
echo "Generated by \`scripts/extension-match-inventory.sh\`."
echo
echo "## Enum Match Occurrences"
echo
echo "| Pattern | Occurrences |"
echo "|---------|-------------|"

count_pattern "\`ActorKindId::\`" "ActorKindId::" "${SEARCH_DIRS[@]}"
count_pattern "\`ActorField::\`" "ActorField::" "${SEARCH_DIRS[@]}"
count_pattern "\`ValueType::\`" "ValueType::" "${SEARCH_DIRS[@]}"
count_pattern "\`ShapeKind::\`" "ShapeKind::" "${SEARCH_DIRS[@]}"
count_pattern "\`GroupHandlerId::\`" "GroupHandlerId::" "${SEARCH_DIRS[@]}"
count_pattern "\`TrackFieldRef::\`" "TrackFieldRef::" "${SEARCH_DIRS[@]}"
count_pattern "\`TrackFieldMut::\`" "TrackFieldMut::" "${SEARCH_DIRS[@]}"
count_pattern "\`PropertyValue::\`" "PropertyValue::" "${SEARCH_DIRS[@]}"
count_pattern "\`RenderCommand::\`" "RenderCommand::" "${SEARCH_DIRS[@]}"

echo
echo "## String Dispatch Occurrences"
echo
echo "| Pattern | Occurrences |"
echo "|---------|-------------|"

count_pattern "\`type_name() ==\`" "type_name\(\) ==" "${SEARCH_DIRS[@]}"
count_pattern "\`actor_type ==\`" "actor_type ==" "${SEARCH_DIRS[@]}"
count_pattern "\`ty == \"...\"\`" 'ty == "' "${SEARCH_DIRS[@]}"

echo
echo "## Match Site Files (ActorKindId / ActorField / ValueType / ShapeKind)"
echo
echo "| File | Matches |"
echo "|------|---------|"

rg -l "ActorKindId::|ActorField::|ValueType::|ShapeKind::" "${SEARCH_DIRS[@]}" 2>/dev/null \
    | while IFS= read -r file; do
        count="$(rg -o "ActorKindId::|ActorField::|ValueType::|ShapeKind::" "$file" | wc -l | tr -d ' ')"
        rel="${file#"$ROOT"/}"
        printf '| %s | %s |\n' "$rel" "$count"
    done \
    | sort -t '|' -k3 -rn
