#!/usr/bin/env bash
# Discover dogfood review runs and emit a hypothesis/worklist markdown file.
#
# Usage:
#   bash scripts/review-discover.sh [output.md]
#
# The generated file is an agent-friendly index: it extracts the brief,
# hypothesis, variants, review status, and existing comments from each run so
# the next agent can decide what to start, resume, or promote.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
RUNS_DIR="$PROJECT_DIR/dogfood/runs"
OUTPUT="${1:-$PROJECT_DIR/dogfood/review-hypotheses.md}"

if [[ ! -d "$RUNS_DIR" ]]; then
  echo "runs directory not found: $RUNS_DIR" >&2
  exit 2
fi

OUT_ABS="$(cd "$(dirname "$OUTPUT")" && pwd)/$(basename "$OUTPUT")"

# Collect stable output before atomically replacing the target.
TMP_OUT="$(mktemp)"
trap 'rm -f "$TMP_OUT"' EXIT

{
cat <<'MD'
# Review Run Discovery

Generated by `scripts/review-discover.sh` from the local `dogfood/runs/`
directory. This file is a worklist, not a review decision.

MD

RUN_COUNT=0
for RUN_DIR in "$RUNS_DIR"/*/; do
  RUN_NAME="$(basename "$RUN_DIR")"
  [[ "$RUN_NAME" == "README.md" ]] && continue
  RUN_COUNT=$((RUN_COUNT + 1))
  echo "## $RUN_NAME"
  echo
  echo "- **Run directory:** \`dogfood/runs/$RUN_NAME/\`"

  BRIEF_FILE="$RUN_DIR/brief.md"
  if [[ -f "$BRIEF_FILE" ]]; then
    BRIEF="$(head -n 1 "$BRIEF_FILE")"
    echo "- **Brief:** ${BRIEF:-No brief text found.}"
  fi

  RUN_FILE="$RUN_DIR/run.md"
  if [[ -f "$RUN_FILE" ]]; then
    HYPOTHESIS="$(grep -iE '^(#+ )?hypothesis' "$RUN_FILE" | head -n 1 || true)"
    if [[ -n "$HYPOTHESIS" ]]; then
      echo "- **Hypothesis:** ${HYPOTHESIS}"
    fi
  fi

  VARIANTS=()
  while IFS= read -r AMX; do
    VARIANTS+=("$(basename "$AMX")")
  done < <(find "$RUN_DIR" -maxdepth 1 -type f \( -name '*.amx' -o -name '*.proposed' -o -name '*.amx.proposed' \) | sort)
  if [[ ${#VARIANTS[@]} -gt 0 ]]; then
    echo "- **Variants:** ${VARIANTS[*]}"
  fi

  if [[ -f "$RUN_DIR/review.done" ]]; then
    echo "- **Status:** complete (review.done)"
  else
    echo "- **Status:** open"
  fi

  if [[ -f "$RUN_DIR/review.json" ]]; then
    COMMENT_COUNT="$(grep -o '"note"' "$RUN_DIR/review.json" | wc -l | tr -d ' ')"
    echo "- **Committed comments:** ${COMMENT_COUNT}"
  fi

  echo
done

if [[ "$RUN_COUNT" -eq 0 ]]; then
  echo "No review runs found."
  echo
fi

cat <<'MD'
## Suggested Next Steps

1. Start with an open run that has a clear brief and a `run.md` hypothesis.
2. Validate variants with `cargo run --bin animatix -- check ...`.
3. For GUI reviewers, use `bash scripts/dogfood-review.sh <slug>`.
4. For external reviewers, use `bash scripts/review-report.sh <slug>`.
5. After a review, update `run.md` and `review.md`, then re-run this script.
MD
} > "$TMP_OUT"

mv "$TMP_OUT" "$OUT_ABS"
echo "Wrote review discovery worklist: $OUT_ABS"
