#!/usr/bin/env python3
"""Local static server for the Animatix web demo with production-like serving:

- correct `application/wasm` MIME type (enables instantiateStreaming)
- transparent brotli negotiation: serves the precompressed `.br` twin when
  the client advertises `Accept-Encoding: br` (a CDN does the same)
- cache headers that keep the edit-and-reload loop working: generated engine
  artifacts (`.wasm`, `pkg*/**.js`) are cacheable, while pages, stylesheets and
  `.amx` scene sources must be revalidated — a five-minute cache on a scene file
  means your edit appears to do nothing

Usage: python3 scripts/serve-web.py [port] [root]  (default 8124, serves web/)
"""
import http.server
import os
import sys

WEB_DIR = os.environ.get("SERVE_ROOT") or os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "web"
)

MIME = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json",
    ".wasm": "application/wasm",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".amx": "text/plain; charset=utf-8",
    ".ttf": "font/ttf",
    ".otf": "font/otf",
}

# Generated by scripts/build-web.sh: expensive to rebuild, safe to cache.
CACHEABLE = ".wasm"


def cache_control(path):
    generated = (
        path.endswith(CACHEABLE)
        or "/pkg" in path.replace(os.sep, "/")
        or path.endswith(".wasm.br")
    )
    if generated:
        return "public, max-age=300"
    return "no-cache"


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=WEB_DIR, **kwargs)

    def guess_type(self, path):
        ext = os.path.splitext(path)[1].lower()
        return MIME.get(ext, "application/octet-stream")

    def send_head(self):
        # brotli negotiation: prefer the precompressed twin when present
        path = self.translate_path(self.path)
        accepts_br = "br" in self.headers.get("Accept-Encoding", "")
        if accepts_br and os.path.isfile(path) and not path.endswith(".br"):
            br_path = path + ".br"
            if os.path.isfile(br_path):
                # serve file.br with the original's type + Content-Encoding
                f = open(br_path, "rb")
                try:
                    self.send_response(200)
                    self.send_header("Content-Type", self.guess_type(path))
                    self.send_header("Content-Encoding", "br")
                    self.send_header("Content-Length", str(os.fstat(f.fileno()).st_size))
                    self.send_header("Vary", "Accept-Encoding")
                    # end_headers() adds Cache-Control once; adding it here too
                    # would send the header twice
                    self.end_headers()
                    return f
                except Exception:
                    f.close()
                    raise
        return super().send_head()

    def end_headers(self):
        self.send_header("Cache-Control", cache_control(self.translate_path(self.path)))
        super().end_headers()

    def log_message(self, fmt, *args):
        sys.stderr.write("[serve-web] %s\n" % (fmt % args))


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8124
    if len(sys.argv) > 2:
        WEB_DIR = os.path.abspath(sys.argv[2])
    server = http.server.ThreadingHTTPServer(("127.0.0.1", port), Handler)
    print(f"serving {WEB_DIR} at http://127.0.0.1:{port}/")
    server.serve_forever()
