#!/usr/bin/env python3
"""Local static server for the Animatix web demo with production-like serving:

- correct `application/wasm` MIME type (enables instantiateStreaming)
- transparent brotli negotiation: serves the precompressed `.br` twin when
  the client advertises `Accept-Encoding: br` (a CDN does the same)
- cache headers that keep the edit-and-reload loop working: generated engine
  artifacts (`.wasm`, `pkg*/**.js`) are cacheable in production mode, while
  pages, stylesheets and `.amx` scene sources must be revalidated.
- `--no-cache` mode (default in local dev): sends no-cache headers for all
  resources so rebuilds and edits take effect immediately without clearing browser cache.
- staleness detection: checks if `web/pkg` wasm binary is older than `crates/`
  engine sources and warns loudly on startup and via HTTP headers.

Usage:
  python3 scripts/serve-web.py [port] [root] [--cache] [--no-cache]
  (default port 8124, serves web/, no-cache default)
"""
import argparse
import http.server
import os
import subprocess
import sys

WEB_DIR = os.environ.get("SERVE_ROOT") or os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "web"
)

MIME = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json",
    ".wasm": "application/wasm",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".amx": "text/plain; charset=utf-8",
    ".ttf": "font/ttf",
    ".otf": "font/otf",
}

# Generated by scripts/build-web.sh: expensive to rebuild, safe to cache in prod.
CACHEABLE = ".wasm"

NO_CACHE_MODE = True
WASM_STALENESS = None


def check_wasm_staleness(web_dir):
    """Check if web/pkg wasm files are missing or older than crates/ engine source."""
    repo_root = os.path.dirname(os.path.abspath(web_dir))
    crates_dir = os.path.join(repo_root, "crates")
    if not os.path.isdir(crates_dir):
        return None

    try:
        out = subprocess.check_output(
            ["git", "log", "-1", "--format=%ct|%h|%s", "crates/"],
            cwd=repo_root,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        parts = out.split("|", 2)
        crates_ts = int(parts[0])
        crates_hash = parts[1]
        crates_msg = parts[2]
    except Exception:
        return None

    results = []
    for pkg_name in ("pkg", "pkg-slim"):
        pkg_dir = os.path.join(web_dir, pkg_name)
        wasm = os.path.join(pkg_dir, "animatix_web_bg.wasm")
        if not os.path.isfile(wasm):
            results.append((pkg_name, "missing", 0))
        else:
            mtime = os.path.getmtime(wasm)
            if crates_ts > mtime:
                results.append((pkg_name, "stale", mtime))
            else:
                results.append((pkg_name, "fresh", mtime))

    return {
        "crates_ts": crates_ts,
        "crates_hash": crates_hash,
        "crates_msg": crates_msg,
        "results": results,
    }


def cache_control(path):
    if NO_CACHE_MODE:
        return "no-cache, no-store, must-revalidate"
    generated = (
        path.endswith(CACHEABLE)
        or "/pkg" in path.replace(os.sep, "/")
        or path.endswith(".wasm.br")
    )
    if generated:
        return "public, max-age=300"
    return "no-cache"


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=WEB_DIR, **kwargs)

    def guess_type(self, path):
        ext = os.path.splitext(path)[1].lower()
        return MIME.get(ext, "application/octet-stream")

    def send_head(self):
        # brotli negotiation: prefer the precompressed twin when present
        path = self.translate_path(self.path)
        accepts_br = "br" in self.headers.get("Accept-Encoding", "")
        if accepts_br and os.path.isfile(path) and not path.endswith(".br"):
            br_path = path + ".br"
            if os.path.isfile(br_path):
                # serve file.br with the original's type + Content-Encoding
                f = open(br_path, "rb")
                try:
                    self.send_response(200)
                    self.send_header("Content-Type", self.guess_type(path))
                    self.send_header("Content-Encoding", "br")
                    self.send_header("Content-Length", str(os.fstat(f.fileno()).st_size))
                    self.send_header("Vary", "Accept-Encoding")
                    self.end_headers()
                    return f
                except Exception:
                    f.close()
                    raise
        return super().send_head()

    def end_headers(self):
        self.send_header("Cache-Control", cache_control(self.translate_path(self.path)))
        # Attach staleness header if WASM artifacts are out-of-date
        if WASM_STALENESS and any(s == "stale" for _, s, _ in WASM_STALENESS["results"]):
            if "/pkg" in self.path:
                self.send_header("X-Animatix-Wasm-Stale", "true")
        super().end_headers()

    def log_message(self, fmt, *args):
        sys.stderr.write("[serve-web] %s\n" % (fmt % args))


def print_staleness_banner(staleness):
    stale_items = [name for name, status, _ in staleness["results"] if status == "stale"]
    missing_items = [name for name, status, _ in staleness["results"] if status == "missing"]
    if not stale_items and not missing_items:
        return

    import datetime
    crates_dt = datetime.datetime.fromtimestamp(staleness["crates_ts"])
    print("\n" + "=" * 72, file=sys.stderr)
    if missing_items:
        print(f"⚠️  WARNING: WASM package(s) missing: {', '.join(missing_items)}", file=sys.stderr)
    if stale_items:
        print(f"⚠️  WARNING: web/pkg wasm binary is older than crates/ engine source!", file=sys.stderr)
        print(f"   Stale packages: {', '.join(stale_items)}", file=sys.stderr)
        print(f"   Latest engine:  {crates_dt.strftime('%Y-%m-%d %H:%M:%S')} [{staleness['crates_hash']}]", file=sys.stderr)
        print(f"   Scenes using newer syntax (e.g. 'settle-in') may fail in browser.", file=sys.stderr)
    print(f"   To rebuild quickly:", file=sys.stderr)
    print(f"     scripts/ensure-web-pkg.sh --dev", file=sys.stderr)
    print("=" * 72 + "\n", file=sys.stderr)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Animatix local web server")
    parser.add_argument("port", nargs="?", type=int, default=8124, help="Port (default: 8124)")
    parser.add_argument("root", nargs="?", type=str, default=None, help="Root directory (default: web/)")
    parser.add_argument("--cache", action="store_true", help="Enable 5-min caching for .wasm (production simulation)")
    parser.add_argument("--no-cache", action="store_true", help="Disable caching for all files (default)")

    args = parser.parse_args()

    port = args.port
    if args.root:
        WEB_DIR = os.path.abspath(args.root)

    # By default, use no-cache unless --cache is explicitly set
    NO_CACHE_MODE = not args.cache

    WASM_STALENESS = check_wasm_staleness(WEB_DIR)
    if WASM_STALENESS:
        print_staleness_banner(WASM_STALENESS)

    cache_desc = "disabled (live reload mode)" if NO_CACHE_MODE else "enabled (max-age=300 for wasm)"
    print(f"serving {WEB_DIR} at http://127.0.0.1:{port}/ [caching: {cache_desc}]")

    server = http.server.ThreadingHTTPServer(("127.0.0.1", port), Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
